'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class SystemAssets
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("HackSystem.SystemAssets", GetType(SystemAssets).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property AboutMe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AboutMe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property CancelButton_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CancelButton_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property CancelButton_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CancelButton_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property CancelButton_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CancelButton_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property CleanCommandPast_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CleanCommandPast_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property CleanCommandPast_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CleanCommandPast_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property CleanCommandPast_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CleanCommandPast_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property CloseButton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CloseButton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property CommandButton_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CommandButton_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property CommandButton_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CommandButton_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property CommandButton_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CommandButton_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property CommandInputBox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CommandInputBox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property CommandTipBGI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CommandTipBGI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property Console_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Console_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property Console_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Console_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property Console_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Console_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property DefaultUserHead() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DefaultUserHead", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property DefaultUserName() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DefaultUserName", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property HackScript_00() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HackScript_00", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property HackScript_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HackScript_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property HackScript_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HackScript_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property HackScript_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HackScript_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property HackScript_04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HackScript_04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property HackScript_05() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HackScript_05", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property HackScript_06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HackScript_06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property HackScript_07() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HackScript_07", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property HackScript_08() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HackScript_08", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property HackScript_09() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HackScript_09", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property HackScript_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HackScript_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property HackScript_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HackScript_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property HackScript_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HackScript_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property HackScript_13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HackScript_13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property HackScript_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HackScript_14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property HackScript_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HackScript_15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property HackScript_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HackScript_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property HackScript_17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HackScript_17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property HackScript_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HackScript_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property HackScript_19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HackScript_19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property HackScript_20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HackScript_20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property HackScript_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HackScript_21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property HackScript_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HackScript_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property HackSystem() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("HackSystem", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property HackSystemLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HackSystemLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property HeadMask() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HeadMask", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property Last_Down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Last_Down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property Last_Enter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Last_Enter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property Last_Normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Last_Normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property LockUIBGM() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("LockUIBGM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property LoginArea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LoginArea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property LoginButton_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LoginButton_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property LoginButton_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LoginButton_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property LoginButton_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LoginButton_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property LoginDesktop() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("LoginDesktop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property MailBackgroundImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MailBackgroundImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property Mailcon_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mailcon_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property Mailcon_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mailcon_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property Mailcon_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mailcon_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property MicroPhone_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MicroPhone_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property MicroPhone_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MicroPhone_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property MicroPhone_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MicroPhone_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property MicroPhone_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MicroPhone_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property MicroPhone_Off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MicroPhone_Off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property MicroPhone_On() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MicroPhone_On", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property MouseClick() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MouseClick", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property MouseCursor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MouseCursor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property MouseDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MouseDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property MouseEnter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MouseEnter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property Next_Down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Next_Down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property Next_Enter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Next_Enter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property Next_Normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Next_Normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property OKButton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OKButton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property PasswordInputBox_Down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PasswordInputBox_Down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property PasswordInputBox_Enter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PasswordInputBox_Enter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property PasswordInputBox_Normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PasswordInputBox_Normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ScriptIcon_00() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScriptIcon_00", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ScriptIcon_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScriptIcon_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ScriptIcon_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScriptIcon_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ScriptIcon_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScriptIcon_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ScriptIcon_04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScriptIcon_04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ScriptIcon_05() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScriptIcon_05", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ScriptIcon_06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScriptIcon_06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ScriptIcon_07() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScriptIcon_07", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ScriptIcon_08() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScriptIcon_08", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ScriptIcon_09() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScriptIcon_09", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ScriptIcon_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScriptIcon_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ScriptIcon_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScriptIcon_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ScriptIcon_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScriptIcon_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ScriptIcon_13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScriptIcon_13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ScriptIcon_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScriptIcon_14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ScriptIcon_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScriptIcon_15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ScriptIcon_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScriptIcon_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ScriptIcon_17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScriptIcon_17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ScriptIcon_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScriptIcon_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ScriptIcon_19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScriptIcon_19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ScriptIcon_20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScriptIcon_20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ScriptIcon_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScriptIcon_21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ScriptIcon_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScriptIcon_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ScriptStarting() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ScriptStarting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ScriptStoped() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ScriptStoped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SendBtn_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SendBtn_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SendBtn_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SendBtn_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SendBtn_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SendBtn_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SettingButton_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SettingButton_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SettingButton_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SettingButton_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SettingButton_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SettingButton_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ShowConsole() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ShowConsole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property Shutdown() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Shutdown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ShutdownArea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ShutdownArea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ShutdownBGI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ShutdownBGI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ShutdownButton_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ShutdownButton_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ShutdownButton_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ShutdownButton_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ShutdownButton_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ShutdownButton_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ShutdownWindow_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ShutdownWindow_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ShutdownWindow_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ShutdownWindow_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ShutdownWindow_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ShutdownWindow_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SpeechButton_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SpeechButton_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SpeechButton_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SpeechButton_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SpeechButton_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SpeechButton_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartedUp() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("StartedUp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUIWallpaper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUIWallpaper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_27() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_27", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_29() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_29", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_30() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_30", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_33() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_33", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_34() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_34", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_35() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_35", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_36() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_36", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_37() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_37", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_38() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_38", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_39() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_39", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_40() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_40", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_41() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_41", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_42() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_42", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_43() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_43", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_44() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_44", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_45() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_45", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_46() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_46", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_47() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_47", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_49() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_49", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_51() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_51", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_52() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_52", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_53() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_53", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_54() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_54", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_55() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_55", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_56() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_56", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_57() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_57", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_58() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_58", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_59() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_59", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property StartingUp_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartingUp_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SystemMsgBGI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SystemMsgBGI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SystemWallpaper_00() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SystemWallpaper_00", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SystemWallpaper_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SystemWallpaper_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SystemWallpaper_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SystemWallpaper_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SystemWallpaper_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SystemWallpaper_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SystemWallpaper_04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SystemWallpaper_04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SystemWallpaper_05() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SystemWallpaper_05", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SystemWallpaper_06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SystemWallpaper_06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SystemWallpaper_07() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SystemWallpaper_07", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SystemWallpaper_08() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SystemWallpaper_08", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SystemWallpaper_09() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SystemWallpaper_09", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SystemWallpaper_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SystemWallpaper_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SystemWallpaper_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SystemWallpaper_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SystemWallpaper_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SystemWallpaper_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SystemWallpaper_13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SystemWallpaper_13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SystemWallpaper_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SystemWallpaper_14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SystemWallpaper_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SystemWallpaper_15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SystemWallpaper_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SystemWallpaper_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SystemWallpaper_17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SystemWallpaper_17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property SystemWallpaper_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SystemWallpaper_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property Tips() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Tips", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property XYBrowserIcon0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("XYBrowserIcon0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property XYBrowserIcon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("XYBrowserIcon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property XYBrowserIcon2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("XYBrowserIcon2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
